#version 450
#extension GL_ARB_separate_shader_objects : enable
precision highp float;
#extension GL_EXT_scalar_block_layout : enable
layout(set = 0, binding = 0) buffer OutIndirect {
  	uint indexCount;
  	uint instanceCount;
  	uint firstIndex;
  	int vertexOffset;
  	uint firstInstance;
}outIndirect;

layout(set = 0, binding = 1) buffer InIndirect {
  	uint indexCount;
  	uint instanceCount;
  	uint firstIndex;
  	int vertexOffset;
  	uint firstInstance;
}inIndirect;

struct MatrixData {
    mat4 protoMatrix;
};

struct InstanceData {
    mat4 modelMatrix;
    mat4 lastModelMatrix;
    vec4 highlight[10];
};

layout(set = 0, binding = 2) buffer InIndirectMatrix {
    MatrixData instanceModelMatrix[];
}inIndirectMatrix;

layout(set = 0, binding = 3) buffer InHighlightData {
    uvec4 data[];
}inHighlightData;

layout(set = 0, binding = 4) buffer OutIndirectMatrix {
    InstanceData instanceModelMatrix[];
}outIndirectMatrix;

layout(set = 0, binding = 5) buffer GlobalModelMatrices {
    mat4 matrices[];
} globalModelMatrices;

layout(set = 0, binding = 6) buffer LastGlobalModelMatrices {
    mat4 matrices[];
} lastGlobalModelMatrices;

layout(set = 0, binding = 7) buffer LastInIndirectMatrix {
    MatrixData instanceModelMatrix[];
} lastInIndirectMatrix;

layout (local_size_x = 32) in;

void main() {
	uint instanceIndex = gl_GlobalInvocationID.x;

    if (instanceIndex >= 1) {
        return;
    }

    outIndirect.instanceCount = inIndirect.instanceCount;
    for(int i = 0; i < outIndirect.instanceCount; i ++){
        MatrixData cur_data = inIndirectMatrix.instanceModelMatrix[i];
        uint modelIndex = inHighlightData.data[i].w;
        InstanceData out_data;
        out_data.modelMatrix = globalModelMatrices.matrices[modelIndex] * cur_data.protoMatrix;
        out_data.lastModelMatrix = lastGlobalModelMatrices.matrices[modelIndex] * lastInIndirectMatrix.instanceModelMatrix[i].protoMatrix;
        out_data.highlight[0].x = inHighlightData.data[i].x;
        outIndirectMatrix.instanceModelMatrix[i] = out_data;
    }
}
